FROM ubuntu:14.04.2

ENV JAVA_VERSION=8u40 \
    JAVA_BUILD_VERSION=8u40-b25

RUN apt-get update &&  \
    apt-get install -y wget && \
    apt-get clean && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Java 8
RUN wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" \
            http://download.oracle.com/otn-pub/java/jdk/${JAVA_BUILD_VERSION}/jre-${JAVA_VERSION}-linux-x64.tar.gz && \
        tar zxf jre-${JAVA_VERSION}-linux-x64.tar.gz -C /opt/ && \
        rm -f jre-${JAVA_VERSION}-linux-x64.tar.gz && \

    # Set JAVA ENV vars
        echo "export JAVA_HOME=/opt/java" > /etc/profile.d/java_home.sh && \
        echo "export PATH=$PATH:/opt/java/bin" >> /etc/profile.d/java_home.sh && \

    # Link default java to actual java version
        ln -s $(find /opt -name jre*) /opt/java && \
        ln -s /opt/java/bin/java /usr/bin/java && \
        ln -s /opt/java/bin/javac /usr/bin/javac


ADD docker-stop-test-0.1-SNAPSHOT.jar /

CMD java -jar docker-stop-test-0.1-SNAPSHOT.jar